#!/bin/sh
echo "次のデータを入力してenterを押してください"
read -p "ハッシュタグ(eg. #きのこ): " str1
read -p "データ取得開始日(eg. 2020-08-10): " str2
read -p "データ取得終了日(eg. 2020-08-20): " str3
read -p "取得ツイート件数(eg. 100): " str4
TAG=$str1 FROM=$str2 UNTIL=$str3 NUM=$str4
echo "入力されたデータ"
echo $TAG $FROM $UNTIL $NUM
ANIMALS=("cheese" \
         "cock" \
         "dragon-and-cow" \
        "ghostbusters" \
        "pony" \
        "stegosaurus" \
        "turtle" \
        "turkey" \
        "gnu"\
        )   
ANIMAL=${ANIMALS[$(($RANDOM % ${#ANIMALS[*]}))]}
cd ~/Desktop/get_old_tweet
docker-compose run \
    --rm \
    -e TAG=$TAG \
    -e FROM=$FROM \
    -e UNTIL=$UNTIL \
    -e NUM=$NUM \
    -e ANIMAL=$ANIMAL \
    python3 \
    python /root/opt/got3.py && \
    cowsay -f  $ANIMAL “ツイートを収集したよ” 
cp opt/tweet_test.csv ~/Desktop
rm opt/tweet_test.csv
open ~/Desktop/tweet_test.csv